### Check if the drone is ON or OFF
GET http://localhost:5000/is_on
Accept: application/json

### Check drone status (battery, height, etc.)
GET http://localhost:5000/status
Accept: application/json

### Command the drone to take off
GET http://localhost:5000/takeoff
Accept: application/json

### Command the drone to land
GET http://localhost:5000/land
Accept: application/json

### Move the drone (change the direction and distance as needed)
POST http://localhost:5000/move/forward/50
Content-Type: application/json

### Move the drone backward
POST http://localhost:5000/move/backward/50
Content-Type: application/json

### Move the drone left
POST http://localhost:5000/move/left/50
Content-Type: application/json

### Move the drone right
POST http://localhost:5000/move/right/50
Content-Type: application/json

### Move the drone up
POST http://localhost:5000/move/up/50
Content-Type: application/json

### Move the drone down
POST http://localhost:5000/move/down/50
Content-Type: application/json

### Check the live video feed (this will not return a JSON response)
GET http://localhost:5000/video_feed
